spring:
  jpa:
    show-sql: true
    database: mysql
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        jdbc:
          time_zone: Asia/Seoul
        format_sql: true
        default_batch_fetch_size: 1000 #최적화 옵션
    open-in-view: false
  datasource:
    url: jdbc:mysql://localhost:3306/test
    username: root
    password: strongpassword
    driver-class-name: com.mysql.cj.jdbc.Driver
